# Site settings
title: Home Remodeling Sales Trainer
email: your-email@example.com
description: >-
  Interactive training tool to help home remodeling sales representatives 
  improve their closing percentage through realistic scenarios.
baseurl: "/convo-game" # the subpath of your site for GitHub Pages
url: "https://tim-amredev.github.io" # the base hostname for GitHub Pages

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  scenarios:
    output: true

# Default layouts
defaults:
  - scope:
      path: ""
    values:
      layout: default

